### ISSUE TITLE
Error with order declaration

### ISSUE THREAD

**Issue by sirenkovladd** [putoutjs/minify#21] opened 2024-06-10 00:13 UTC
- **Version** (`npm -v`): 10.5.2
- **Node Version** `node -v`: v20.13.1
- **OS** (`uname -a` on Linux): Darwin arm64

Error with order declaration

```js
import { minify } from "@putout/minify";

const source = `const q = 1,
  signalOptions = {};
function createSignal(e, n) {
  return Object.assign({}, signalOptions, n);
}
const transPending = createSignal(!q);
console.log(transPending[q] && transPending)`;

eval(source);
const result = minify(source);
console.log(result);
eval(result);
```

```sh
❯ node i.js
undefined
const{assign:a}=Object,A=d(!q);const q=1,c={};function d(e,n){return a({},c,n)}console.log(A[q]&&A);
undefined:1
const{assign:a}=Object,A=d(!q);const q=1,c={};function d(e,n){return a({},c,n)}console.log(A[q]&&A);
                            ^

ReferenceError: Cannot access 'q' before initialization
```

**Comment by coderaiser** [comment] 2024-06-10 20:11
Duplicate of #18, I have no solution other then turning `mergeVariables` off:

```js
import { minify } from "@putout/minify";

const source = `const q = 1,
  signalOptions = {};
function createSignal(e, n) {
  return Object.assign({}, signalOptions, n);
}
const transPending = createSignal(!q);
console.log(transPending[q] && transPending)`;

eval(source);
const result = minify(source, {
    mergeVariables: false,
});
console.log(result);
eval(result);
```

If you have - send PR.

**Closed as completed by coderaiser** 2024-06-10 20:11 UTC
Labels: duplicate

**Comment by sirenkovladd** [comment] 2024-06-10 20:54
Well, this is not a problem if the solution is only turning `mergeVariables` off
But I think that this option should be enabled by default, since using it will lead to errors and a bad experience

**Comment by coderaiser** [comment] 2024-06-11 07:10
Absolutely agree with you! Are you up to a PR? Theres a couple places that should be changed:
- README
- default options in lib
- a couple tests (one with disabling the flag, should be changed to enabling the flag, maybe with other examples, so by default we disable for not working examples, and sometimes can enable for working)

**Comment by coderaiser** [comment] 2024-06-12 14:29
Fixed in latest version of `@putout/minify`
